kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: notebooks
spec:
  host: jupyterhub-t.apps.ddb.mandate.prod.jason.dnb.de
  to:
    kind: Service
    name: proxy-public
    weight: 100
  port:
    targetPort: 8000
  tls:
    termination: edge
  wildcardPolicy: None
