kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ddbjupyterlabproxy
spec:
  source:
    type: Dockerfile
    dockerfile: |
      FROM quay.io/jupyterhub/configurable-http-proxy:4.6.2
      USER root
      RUN apk upgrade --no-cache
  strategy:
    type: Docker
  triggers:
  - type: ConfigChange
  output:
    to:
      kind: ImageStreamTag
      name: ddbjupyterlabproxy:4.6.2
