kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ddbjupyterlabhub
spec:
  source:
    type: Dockerfile
    dockerfile: |
      FROM quay.io/jupyterhub/k8s-hub:3.3.8
      USER root
      RUN apt-get update && apt-get -y upgrade
  strategy:
    type: Docker
  triggers:
  - type: ConfigChange
  output:
    to:
      kind: ImageStreamTag
      name: ddbjupyterlabhub:3.3.8
